USE db_ab10ba_kbarreradev
GO

BEGIN TRAN MEJORAPROD
SELECT * 
INTO #TEMPPRODUCTOS
FROM PRODUCTO ORDER BY idProducto ASC
IF @@ERROR != 0
BEGIN
	ROLLBACK TRAN MEJORAPROD
	PRINT 'HUBO UN ERROR AL INSERTAR EN LA TEMPORAL'
END

INSERT INTO PRODUCTOS
SELECT * FROM #TEMPPRODUCTOS
IF @@ERROR != 0
BEGIN
	ROLLBACK TRAN MEJORAPROD
	PRINT 'HUBO UN ERROR AL INSERTAR EN LA NUEVA TABLA'
END

DECLARE @SECUENCIAL INT
SELECT @SECUENCIAL = MAX(idProducto) FROM PRODUCTOS
IF ISNULL(@SECUENCIAL, '') = ''
BEGIN
	ROLLBACK TRAN MEJORAPROD
	PRINT 'NO EXISTEN PRODUCTOS'
END

INSERT SECUENCIAL (SE_TABLE, SE_SEQ) VALUES ('PRODUCTOS', @SECUENCIAL)
IF @@ERROR != 0
BEGIN
	ROLLBACK TRAN MEJORAPROD
	PRINT 'HUBO UN ERROR AL INSERTAR EL SECUENCIAL'
END

UPDATE PRODUCTOS SET estado = 1
IF @@ERROR != 0
BEGIN
	ROLLBACK TRAN MEJORAPROD
	PRINT 'HUBO UN ERROR AL ACTUALIZAR EL ESTADO'
END

COMMIT TRAN MEJORAPROD
DROP TABLE #TEMPPRODUCTOS

SELECT * FROM SECUENCIAL WHERE SE_TABLE = 'PRODUCTOS'