USE db_ab10ba_kbarreradev
GO

BEGIN TRAN MEJORAVENTA
SELECT * 
INTO #TEMPVENTAS
FROM VENTA ORDER BY nVenta ASC
IF @@ERROR != 0
BEGIN
	ROLLBACK TRAN MEJORAVENTA
	PRINT 'HUBO UN ERROR AL INSERTAR EN LA TEMPORAL'
END

INSERT INTO VENTAS
SELECT * FROM #TEMPVENTAS
IF @@ERROR != 0
BEGIN
	ROLLBACK TRAN MEJORAVENTA
	PRINT 'HUBO UN ERROR AL INSERTAR EN LA NUEVA TABLA'
END

DECLARE @SECUENCIAL INT
SELECT @SECUENCIAL = MAX(nVenta) FROM VENTAS
IF ISNULL(@SECUENCIAL, '') = ''
BEGIN
	ROLLBACK TRAN MEJORAVENTA
	PRINT 'NO EXISTEN PRODUCTOS'
END

INSERT SECUENCIAL (SE_TABLE, SE_SEQ) VALUES ('VENTAS', @SECUENCIAL)
IF @@ERROR != 0
BEGIN
	ROLLBACK TRAN MEJORAVENTA
	PRINT 'HUBO UN ERROR AL INSERTAR EL SECUENCIAL'
END

COMMIT TRAN MEJORAVENTA
DROP TABLE #TEMPVENTAS

SELECT * FROM SECUENCIAL WHERE SE_TABLE = 'VENTAS'
SELECT * FROM VENTAS