USE db_ab10ba_kbarreradev
GO

BEGIN TRAN MEJORADETALLESVENTA
SELECT * 
INTO #TEMPDETALLEVENTAS
FROM DETALLEVENTA ORDER BY nVenta ASC
IF @@ERROR != 0
BEGIN
	ROLLBACK TRAN MEJORADETALLESVENTA
	PRINT 'HUBO UN ERROR AL INSERTAR EN LA TEMPORAL'
END

INSERT INTO DETALLEVENTAS
SELECT * FROM #TEMPDETALLEVENTAS
IF @@ERROR != 0
BEGIN
	ROLLBACK TRAN MEJORADETALLESVENTA
	PRINT 'HUBO UN ERROR AL INSERTAR EN LA NUEVA TABLA'
END



COMMIT TRAN MEJORADETALLESVENTA
DROP TABLE #TEMPDETALLEVENTAS

SELECT * FROM SECUENCIAL WHERE SE_TABLE = 'DETALLEVENTA'
SELECT * FROM DETALLEVENTAS