USE [farmaciahorro_ispro2]
GO

/****** Object:  Table [dbo].[DETALLEVENTA]    Script Date: 28/02/2025 11:21:51 a. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DETALLEVENTAS](
	[nDetalleV] [smallint] NOT NULL,
	[nVenta] [int] NOT NULL,
	[producto] [int] NULL,
	[cantidad] [int] NULL,
	[precio] [decimal](18, 2) NULL,
	[subtotal] [decimal](18, 2) NULL,
 CONSTRAINT [PK_DETALLEVENTAS] PRIMARY KEY CLUSTERED 
(
	[nDetalleV] ASC,
	[nVenta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DETALLEVENTAS]  WITH CHECK ADD  CONSTRAINT [FK_DETALLEVENTAS_PRODUCTOS] FOREIGN KEY([producto])
REFERENCES [dbo].[PRODUCTOS] ([idProducto])
GO

ALTER TABLE [dbo].[DETALLEVENTAS] CHECK CONSTRAINT [FK_DETALLEVENTAS_PRODUCTOS]
GO

ALTER TABLE [dbo].[DETALLEVENTAS]  WITH CHECK ADD  CONSTRAINT [FK_DETALLEVENTAS_VENTAS] FOREIGN KEY([nVenta])
REFERENCES [dbo].[VENTAS] ([nVenta])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[DETALLEVENTAS] CHECK CONSTRAINT [FK_DETALLEVENTAS_VENTAS]
GO


